# Generated by Django 3.0 on 2021-12-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Desc', models.CharField(max_length=300)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
